### ISSUE TITLE
Error messages: batterycharge, carfinder, and statusreport not found

### ISSUE THREAD

**Issue by cbho** [arjenvrh/audi_connect_ha#5]
Hi,
trying to get audi_connect to work - but get the error messages shown below.
My A3 is connected to "my audi" and I can track location data etc. using the audi app - so the connection is available.

My setup is 
hass.io: 0.94.3
audi_connect_ha:  all files updates as pr. today

configuration.yaml:
(have tried without "region", with EU, with DA, and DK - no difference - and yes, I checked my VIN number a zillion times).

Any suggestions what could be the problem?

Regards,
Chr.

```
audiconnect:
  username: '[not_published_here]'
  password: '[not_published_here]'
  region: EU
  scan_interval:
    minutes: 2
  name:
    [not_published_here]: 'Audi A3'
```

```
API error: {'errorCode': 'batterycharge.bs.entitynotfound', 'description': "entity '[not_published_here]' not found."}
7:57 PM custom_components/audiconnect/audi_connect_account.py (ERROR) - message first occured at 7:55 PM and shows up 2 times
API error: {'errorCode': 'CF.security.9007', 'description': 'The service: carfinder_v1 for VIN: [not_published_here] could not be found.'}
7:57 PM custom_components/audiconnect/audi_connect_account.py (ERROR) - message first occured at 7:55 PM and shows up 2 times
API error: {'errorCode': 'VSR.security.9007', 'description': 'The service: statusreport_v1 for VIN: [not_published_here] could not be found.'}
7:57 PM custom_components/audiconnect/audi_connect_account.py (ERROR) - message first occured at 7:55 PM and shows up 2 times
```
