### ISSUE TITLE
Fails to lock/unlock vehicle

### ISSUE THREAD

**Issue by dsantanu** [arjenvrh/audi_connect_ha#80]
It's constantly failing to lock/unlock the car, resulting an hr. long suspension after every 5 failed attempts. When I lock/unlock the car from myAudi app, it always asks for the PIN before proceed:

![lock_pin](https://user-images.githubusercontent.com/4650237/119246066-1a7f0880-bb76-11eb-921c-8641212d88b0.jpg)

I don't think **S-PIN** alone can do that and I don't see any option for `lock.<myCar>_door_lock` to set that up?  Ideally, clicking the button, should represent the PIN entry screen, like the security system integration dose for arm/disarm functionality. Am I missing something here or didn't configure it properly?

-S

**Comment by JamieP83** [comment]
same issue.
im using this script, but not sure what to pass for my pin?


```
audi_service_lock:
  sequence: 
    - service: audiconnect.execute_vehicle_action
      data:
        vin: !secret audisq5vin
        action: 'lock'

audi_service_unlock:
  sequence: 
    - service: audiconnect.execute_vehicle_action
      data:
        vin: !secret audisq5vin
        action: 'unlock'
```
